name: Build and deploy Node.js app to Azure Web App - zalendovs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_OPTIONS: --max-old-space-size=4096  # Fix: Correct hyphenation

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'  # Cache dependencies for faster builds

      - name: Clean potential symlinks
        run: |
          find . -type l -delete
          rm -rf node_modules
          rm -rf */node_modules

      - name: Install dependencies
        run: npm ci  # Clean install for production

      - name: Build application
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Create optimized deployment package
        run: |
          # Create clean deployment folder
          mkdir -p deployment
          
          # Copy only necessary files
          cp -r package*.json server.js config/ deployment/
          
          # Copy built client files if they exist
          if [ -d "dist" ]; then cp -r dist/ deployment/client; fi
          if [ -d "build" ]; then cp -r build/ deployment/client; fi
          
          # Zip the deployment folder (excluding hidden files)
          cd deployment && zip -r ../release.zip . -x ".*" -x "__MACOSX"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: |
          mkdir -p deployment
          unzip -q release.zip -d deployment

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zalendovs'
          slot-name: 'Production'
          package: deployment  # Deploy from clean folder
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A50A8EB01DB84963A8563EE14836C1CE }}
