name: Build and deploy Node.js app to Azure Web App - zalendovs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Clean node_modules
        run: |
          rm -rf node_modules
          rm -rf client/node_modules

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Create deployment package
        run: |
          # Exclude node_modules and other unnecessary files
          zip -r release.zip . \
            -x '*node_modules*' \
            -x '*.git*' \
            -x '*.log*' \
            -x '*.env*' \
            -x '*.vscode*' \
            -x '*__pycache__*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip -q release.zip
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zalendovs'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1F7C564121BC41E292AB299957787336 }}
